name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/movies:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set working directory
        run: cd ../..

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply tfplan -auto-approve

      - name: Set up Terraform environment
        run: |
          echo ${{ secrets.AZURE_CREDENTIALS }} > azure_credentials.json
          echo ${{ secrets.TF_VAR_ARM_CLIENT_ID }} > ARM_CLIENT_ID
          echo ${{ secrets.TF_VAR_ARM_CLIENT_SECRET }} > ARM_CLIENT_SECRET
          echo ${{ secrets.TF_VAR_ARM_SUBSCRIPTION_ID }} > ARM_SUBSCRIPTION_ID
          echo ${{ secrets.TF_VAR_ARM_TENANT_ID }} > ARM_TENANT_ID

      - name: Configure Azure credentials
        run: |
          az login --service-principal --username "$(cat ARM_CLIENT_ID)" --password "$(cat ARM_CLIENT_SECRET)" --tenant "$(cat ARM_TENANT_ID)"
          az account set --subscription "$(cat ARM_SUBSCRIPTION_ID)"
